import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1791312997492 implements MigrationInterface {
    name = 'InitialSchema1791312997492'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "personal_data" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "phone" character varying(30), "avatar_url" text, "date_of_birth" date, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "REL_78ca212d8f4f2679c9c5985269" UNIQUE ("user_id"), CONSTRAINT "PK_1e2cf868aa2878d017400387a89" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_system_role_enum" AS ENUM('user', 'admin')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "system_role" "public"."user_system_role_enum" NOT NULL DEFAULT 'user', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_user_email" ON "user" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."bond_member_role_enum" AS ENUM('progenitor', 'coordinator', 'third_party')`);
        await queryRunner.query(`CREATE TABLE "bond_member" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bond_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role" "public"."bond_member_role_enum" NOT NULL, "joined_at" TIMESTAMP WITH TIME ZONE, "left_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ea1288119ada5d67599c00694ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "children" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bond_id" uuid NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "date_of_birth" date, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8c5a7cbebf2c702830ef38d22b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."bond_agreement_type_enum" AS ENUM('formal', 'informal')`);
        await queryRunner.query(`CREATE TABLE "bond" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "agreement_type" "public"."bond_agreement_type_enum" NOT NULL, "court_case_ref" character varying(255), "start_date" date, "end_date" date, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2a4d050cae7f0326222053ae2b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."report_status_enum" AS ENUM('requested', 'in_progress', 'completed', 'delivered')`);
        await queryRunner.query(`CREATE TABLE "report" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bond_id" uuid NOT NULL, "requested_by" uuid NOT NULL, "generated_by" uuid, "date_from" date NOT NULL, "date_to" date NOT NULL, "status" "public"."report_status_enum" NOT NULL DEFAULT 'requested', "file_url" text, "generated_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_99e4d0bea58cba73c57f935a546" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "bond_id" uuid, "type" character varying(50) NOT NULL, "title" character varying(255) NOT NULL, "body" text NOT NULL, "ref_entity_type" character varying(50) NOT NULL, "ref_entity_id" uuid, "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_notification_ref_entity" ON "notification" ("ref_entity_id") `);
        await queryRunner.query(`CREATE TYPE "public"."auth_third_party_status_enum" AS ENUM('active', 'suspended', 'revoked')`);
        await queryRunner.query(`CREATE TABLE "auth_third_party" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bond_id" uuid NOT NULL, "user_id" uuid NOT NULL, "authorized_by" uuid NOT NULL, "start_date" date, "end_date" date, "status" "public"."auth_third_party_status_enum" NOT NULL DEFAULT 'active', "scope_note" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3ebc350626d5a63d1010b7ef2c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "activity_child" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activity_id" uuid NOT NULL, "child_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_963e1d93723fb80b4f635b74950" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "color" character varying(7), "icon" character varying(50), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_23c05c292c439d77b0de816b500" UNIQUE ("name"), CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."activity_type_enum" AS ENUM('event', 'obligation')`);
        await queryRunner.query(`CREATE TYPE "public"."activity_status_enum" AS ENUM('created', 'assigned', 'in_progress', 'verify', 'done', 'overdue')`);
        await queryRunner.query(`CREATE TYPE "public"."activity_criticality_enum" AS ENUM('critical', 'high', 'medium', 'low')`);
        await queryRunner.query(`CREATE TYPE "public"."activity_resolved_status_enum" AS ENUM('created', 'assigned', 'in_progress', 'verify', 'done', 'overdue')`);
        await queryRunner.query(`CREATE TABLE "activity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bond_id" uuid NOT NULL, "category_id" uuid NOT NULL, "type" "public"."activity_type_enum" NOT NULL, "status" "public"."activity_status_enum" NOT NULL DEFAULT 'created', "criticality" "public"."activity_criticality_enum" NOT NULL DEFAULT 'medium', "title" character varying(255) NOT NULL, "description" text NOT NULL, "created_by" uuid NOT NULL, "assigned_to" uuid, "scheduled_start" TIMESTAMP WITH TIME ZONE, "scheduled_end" TIMESTAMP WITH TIME ZONE, "deadline" TIMESTAMP WITH TIME ZONE, "notif_before" interval, "notif_after" interval, "assigned_confirmed" boolean NOT NULL DEFAULT false, "confirmed_at" TIMESTAMP WITH TIME ZONE, "cancelled_at" TIMESTAMP WITH TIME ZONE, "cancelled_by" uuid, "completed_at" TIMESTAMP WITH TIME ZONE, "resolved_status" "public"."activity_resolved_status_enum", "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_24625a1d6b1b089c8ae206fe467" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."third_activity_participation_participation_status_enum" AS ENUM('asignado', 'confirmado', 'rechazado', 'completado')`);
        await queryRunner.query(`CREATE TABLE "third_activity_participation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "auth_third_id" uuid NOT NULL, "activity_id" uuid NOT NULL, "participation_status" "public"."third_activity_participation_participation_status_enum" NOT NULL DEFAULT 'asignado', "confirmed_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_27e07293b94e3725931f7a9de92" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."expense_status_enum" AS ENUM('pending', 'approved', 'rejected', 'paid')`);
        await queryRunner.query(`CREATE TABLE "expense" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bond_id" uuid NOT NULL, "child_id" uuid, "concept" character varying(255) NOT NULL, "description" text, "amount" numeric(12,2) NOT NULL, "expense_date" date NOT NULL, "split_ratio_payer" numeric(5,2) NOT NULL, "split_ratio_other" numeric(5,2) NOT NULL, "status" "public"."expense_status_enum" NOT NULL DEFAULT 'pending', "requested_by" uuid NOT NULL, "approved_by" uuid, "approved_at" TIMESTAMP WITH TIME ZONE, "paid_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_edd925b450e13ea36197c9590fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "expense_attachment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "expense_id" uuid NOT NULL, "file_url" text NOT NULL, "file_name" character varying(255) NOT NULL, "file_type" character varying(50) NOT NULL, "uploaded_by" uuid NOT NULL, "uploaded_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_44caefa2d760da1d5e6b4a006c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_log" ("id" BIGSERIAL NOT NULL, "bond_id" uuid, "user_id" uuid NOT NULL, "entity_type" character varying(50) NOT NULL, "entity_id" uuid, "action" character varying(50) NOT NULL, "old_value" jsonb, "new_value" jsonb, "detail" text, "ip_address" character varying(45), "user_agent" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_07fefa57f7f5ab8fc3f52b3ed0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_audit_bond" ON "audit_log" ("bond_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_entity" ON "audit_log" ("entity_type") `);
        await queryRunner.query(`CREATE TABLE "act_attachment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activity_id" uuid NOT NULL, "file_url" text NOT NULL, "file_name" character varying(255) NOT NULL, "file_type" character varying(50) NOT NULL, "uploaded_by" uuid NOT NULL, "uploaded_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8e1cc937eb63e3cf524bdbcdc23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "personal_data" ADD CONSTRAINT "FK_78ca212d8f4f2679c9c5985269a" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bond_member" ADD CONSTRAINT "FK_4ad469e7e27b06db11bb57aa52f" FOREIGN KEY ("bond_id") REFERENCES "bond"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bond_member" ADD CONSTRAINT "FK_88d6aeaebb3fdb79d014135c8ae" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "children" ADD CONSTRAINT "FK_65cbe1e204bb54e2d5f8dddfae9" FOREIGN KEY ("bond_id") REFERENCES "bond"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report" ADD CONSTRAINT "FK_73cc4c4885b1294374582e03bd9" FOREIGN KEY ("bond_id") REFERENCES "bond"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report" ADD CONSTRAINT "FK_f23e6c3ce6c1ca9981fddc5af51" FOREIGN KEY ("requested_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report" ADD CONSTRAINT "FK_6f9e2913253a9e92fcaa119fdf7" FOREIGN KEY ("generated_by") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_928b7aa1754e08e1ed7052cb9d8" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_2723fe72ff6a51ca9962798a3df" FOREIGN KEY ("bond_id") REFERENCES "bond"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_third_party" ADD CONSTRAINT "FK_f74b6e801fcc5b86acaa448b03f" FOREIGN KEY ("bond_id") REFERENCES "bond"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_third_party" ADD CONSTRAINT "FK_07adff359ade3ab5d960f4b4d8e" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_third_party" ADD CONSTRAINT "FK_08de4002a248eb1da75028f617e" FOREIGN KEY ("authorized_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_child" ADD CONSTRAINT "FK_5438436d1078dbb075b670344ee" FOREIGN KEY ("activity_id") REFERENCES "activity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_child" ADD CONSTRAINT "FK_8772fba65c828dd1dd1a032c5f5" FOREIGN KEY ("child_id") REFERENCES "children"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity" ADD CONSTRAINT "FK_f9ac61dba1002313325a547eda3" FOREIGN KEY ("bond_id") REFERENCES "bond"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity" ADD CONSTRAINT "FK_5d3d888450207667a286922f945" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity" ADD CONSTRAINT "FK_3aed15781cd09de7bfb17a24519" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity" ADD CONSTRAINT "FK_986ab453f90e968a0e35fe3ee07" FOREIGN KEY ("assigned_to") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "third_activity_participation" ADD CONSTRAINT "FK_a7aa1183ef60317cc7062fdd266" FOREIGN KEY ("auth_third_id") REFERENCES "auth_third_party"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "third_activity_participation" ADD CONSTRAINT "FK_82c82de3081bee814f9ddc9160b" FOREIGN KEY ("activity_id") REFERENCES "activity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense" ADD CONSTRAINT "FK_58bf223b351edf140bed39457a1" FOREIGN KEY ("bond_id") REFERENCES "bond"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense" ADD CONSTRAINT "FK_0b855e2698a08efed7175cd885c" FOREIGN KEY ("child_id") REFERENCES "children"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense" ADD CONSTRAINT "FK_884afa46df68d22a0ed19d9d47e" FOREIGN KEY ("requested_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense" ADD CONSTRAINT "FK_ead502e119a93224cc9138514ef" FOREIGN KEY ("approved_by") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense_attachment" ADD CONSTRAINT "FK_e056bb5feed96362a9d19ccd9bb" FOREIGN KEY ("expense_id") REFERENCES "expense"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expense_attachment" ADD CONSTRAINT "FK_7abbb241947617d8c06390a6969" FOREIGN KEY ("uploaded_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD CONSTRAINT "FK_1a56e53f5a1616e7ec9c94d1feb" FOREIGN KEY ("bond_id") REFERENCES "bond"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD CONSTRAINT "FK_cb11bd5b662431ea0ac455a27d7" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "act_attachment" ADD CONSTRAINT "FK_676ca412249833bb144414aa6b8" FOREIGN KEY ("activity_id") REFERENCES "activity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "act_attachment" ADD CONSTRAINT "FK_90e8962c47667219bd3312aa014" FOREIGN KEY ("uploaded_by") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "act_attachment" DROP CONSTRAINT "FK_90e8962c47667219bd3312aa014"`);
        await queryRunner.query(`ALTER TABLE "act_attachment" DROP CONSTRAINT "FK_676ca412249833bb144414aa6b8"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP CONSTRAINT "FK_cb11bd5b662431ea0ac455a27d7"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP CONSTRAINT "FK_1a56e53f5a1616e7ec9c94d1feb"`);
        await queryRunner.query(`ALTER TABLE "expense_attachment" DROP CONSTRAINT "FK_7abbb241947617d8c06390a6969"`);
        await queryRunner.query(`ALTER TABLE "expense_attachment" DROP CONSTRAINT "FK_e056bb5feed96362a9d19ccd9bb"`);
        await queryRunner.query(`ALTER TABLE "expense" DROP CONSTRAINT "FK_ead502e119a93224cc9138514ef"`);
        await queryRunner.query(`ALTER TABLE "expense" DROP CONSTRAINT "FK_884afa46df68d22a0ed19d9d47e"`);
        await queryRunner.query(`ALTER TABLE "expense" DROP CONSTRAINT "FK_0b855e2698a08efed7175cd885c"`);
        await queryRunner.query(`ALTER TABLE "expense" DROP CONSTRAINT "FK_58bf223b351edf140bed39457a1"`);
        await queryRunner.query(`ALTER TABLE "third_activity_participation" DROP CONSTRAINT "FK_82c82de3081bee814f9ddc9160b"`);
        await queryRunner.query(`ALTER TABLE "third_activity_participation" DROP CONSTRAINT "FK_a7aa1183ef60317cc7062fdd266"`);
        await queryRunner.query(`ALTER TABLE "activity" DROP CONSTRAINT "FK_986ab453f90e968a0e35fe3ee07"`);
        await queryRunner.query(`ALTER TABLE "activity" DROP CONSTRAINT "FK_3aed15781cd09de7bfb17a24519"`);
        await queryRunner.query(`ALTER TABLE "activity" DROP CONSTRAINT "FK_5d3d888450207667a286922f945"`);
        await queryRunner.query(`ALTER TABLE "activity" DROP CONSTRAINT "FK_f9ac61dba1002313325a547eda3"`);
        await queryRunner.query(`ALTER TABLE "activity_child" DROP CONSTRAINT "FK_8772fba65c828dd1dd1a032c5f5"`);
        await queryRunner.query(`ALTER TABLE "activity_child" DROP CONSTRAINT "FK_5438436d1078dbb075b670344ee"`);
        await queryRunner.query(`ALTER TABLE "auth_third_party" DROP CONSTRAINT "FK_08de4002a248eb1da75028f617e"`);
        await queryRunner.query(`ALTER TABLE "auth_third_party" DROP CONSTRAINT "FK_07adff359ade3ab5d960f4b4d8e"`);
        await queryRunner.query(`ALTER TABLE "auth_third_party" DROP CONSTRAINT "FK_f74b6e801fcc5b86acaa448b03f"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_2723fe72ff6a51ca9962798a3df"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_928b7aa1754e08e1ed7052cb9d8"`);
        await queryRunner.query(`ALTER TABLE "report" DROP CONSTRAINT "FK_6f9e2913253a9e92fcaa119fdf7"`);
        await queryRunner.query(`ALTER TABLE "report" DROP CONSTRAINT "FK_f23e6c3ce6c1ca9981fddc5af51"`);
        await queryRunner.query(`ALTER TABLE "report" DROP CONSTRAINT "FK_73cc4c4885b1294374582e03bd9"`);
        await queryRunner.query(`ALTER TABLE "children" DROP CONSTRAINT "FK_65cbe1e204bb54e2d5f8dddfae9"`);
        await queryRunner.query(`ALTER TABLE "bond_member" DROP CONSTRAINT "FK_88d6aeaebb3fdb79d014135c8ae"`);
        await queryRunner.query(`ALTER TABLE "bond_member" DROP CONSTRAINT "FK_4ad469e7e27b06db11bb57aa52f"`);
        await queryRunner.query(`ALTER TABLE "personal_data" DROP CONSTRAINT "FK_78ca212d8f4f2679c9c5985269a"`);
        await queryRunner.query(`DROP TABLE "act_attachment"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_entity"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_bond"`);
        await queryRunner.query(`DROP TABLE "audit_log"`);
        await queryRunner.query(`DROP TABLE "expense_attachment"`);
        await queryRunner.query(`DROP TABLE "expense"`);
        await queryRunner.query(`DROP TYPE "public"."expense_status_enum"`);
        await queryRunner.query(`DROP TABLE "third_activity_participation"`);
        await queryRunner.query(`DROP TYPE "public"."third_activity_participation_participation_status_enum"`);
        await queryRunner.query(`DROP TABLE "activity"`);
        await queryRunner.query(`DROP TYPE "public"."activity_resolved_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."activity_criticality_enum"`);
        await queryRunner.query(`DROP TYPE "public"."activity_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."activity_type_enum"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP TABLE "activity_child"`);
        await queryRunner.query(`DROP TABLE "auth_third_party"`);
        await queryRunner.query(`DROP TYPE "public"."auth_third_party_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notification_ref_entity"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TABLE "report"`);
        await queryRunner.query(`DROP TYPE "public"."report_status_enum"`);
        await queryRunner.query(`DROP TABLE "bond"`);
        await queryRunner.query(`DROP TYPE "public"."bond_agreement_type_enum"`);
        await queryRunner.query(`DROP TABLE "children"`);
        await queryRunner.query(`DROP TABLE "bond_member"`);
        await queryRunner.query(`DROP TYPE "public"."bond_member_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_user_email"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_system_role_enum"`);
        await queryRunner.query(`DROP TABLE "personal_data"`);
    }

}
